apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dstaroff
  name: jail
spec:
  storageClassName: local-pv
  resources:
    requests:
      storage: 128Gi
  accessModes:
    - ReadWriteMany
